apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Spike automation

on:
  push:
    branches:
      - "**"

jobs:
  build:
    steps:
      - name: checkout code
        uses: cloudbees-io/checkout@v1

      - name: build code
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        timeout-minutes: 0.5
        run: |
          export GOPATH=$HOME/go
          export PATH=$PATH:$GOPATH/bin
          go version
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/api-server .

      - name: docker login
        id: docker-login-step
        uses: docker://alpine:3.17
        shell: sh
        env:
          DOCKER_USERNAME: ${{ secrets.demo-docker-user }}
          DOCKER_PASSWORD: ${{ secrets.demo-docker-token }}
        run: |
          AUTH=$(echo -n "${DOCKER_USERNAME}:${DOCKER_PASSWORD}" | base64)
          cat << EOF > "$CLOUDBEES_OUTPUTS/dockerconfigjson"
          {
              "auths": {
                  "https://index.docker.io/v1/": {
                      "auth": "${AUTH}"
                  }
              }
          }
          EOF

      - name: docker build and publish
        uses: cloudbees-io/kaniko@v1
        with:
          dockerconfigjson: ${{ steps.docker-login-step.outputs.dockerconfigjson }}
          destination: index.docker.io/swashbuck1r/simple-go-api-server:1.0.3
          labels: maintaner=swashbuck1r
          context: ${{ cloudbees.workspace }}
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1,BUILD_ARG_SPACES='i am a space'
